version: 2.1

jobs:
  build: # name of your job
    machine:
      image: windows-default # Windows machine image
    resource_class: windows.medium
    steps:
      # Commands are run in a Windows virtual machine environment
        - checkout
        - run: Write-Host 'Hello, Windows'
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595
        - run: sleep 595